# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10" # Or whichever Python version you're targeting, matching your setup.py's python_requires

sphinx:
  configuration: docs/conf.py # This points to your conf.py file

python:
  install:
    - requirements: docs/requirements.txt # (Optional) If you have doc-specific requirements (e.g., sphinx, sphinx-rtd-theme)
    - method: pip
      path: . # This tells Read the Docs to install your package from the current directory using pip
              # This is equivalent to 'pip install .' and makes your 'mesalab' package available for autodoc.
