# my_conf_settings.yaml - MESA Lab Configuration


# --- General Settings ---
general_settings:
  input_dir: /home/tnd/mesa-r23.05.1/STRANGE/nad_convos_mid # Directory containing MESA run subdirectories
  output_dir: /home/tnd/mesagrid/mesa_blue_loop/output_mid      # Output base directory for analysis results
  inlist_name: "inlist_project"                                         # Inlist filename to identify runs
  force_reanalysis: True                                                # Set to True to force reanalysis, False to use existing summary files if complete
  debug: True                                                           # Set to True for more verbose logging

# --- Blue Loop Analysis Settings ---
blue_loop_analysis:
  analyze_blue_loop: True
  blue_loop_output_type: "summary"                                      # "all" (detailed files) or "summary" (only summary CSV)

# --- Plotting specific settings ---
plotting_settings:
  generate_heatmaps: True
  generate_plots: True                                                  # General plots (e.g., summary scatter plots)
  generate_hr_diagrams: "drop_zams"                                     # Options: "none", "all", "drop_zams"
  generate_blue_loop_plots_with_bc: True                                # Generate HR diagrams with bolometric corrections for blue loops

# --- GYRE Workflow specific settings ---
gyre_workflow:
  run_gyre_workflow: True
  gyre_config_path: "gyre_config_malor.in"                                    # Path to the GYRE-specific configuration file (relative to cli.py)
  gyre_input_csv_name: "sorted_mass_Z_min_max.csv"                      # Custom name for the GYRE input CSV
  
