# my_settings.yaml
# Configuration for mesa_grid_analyzer - focusing EXCLUSIVELY on Blue Loop BC plots

# --- Required Input/Output Paths ---
# These are essential for the program to find your MESA data and save results.
input_dir: /home/tnehezd/workdir/mesa-r23.05.1/STRANGE/nad_convos_mid
output_dir: /d5/tnehezd/mesa_blue_loop/output
inlist_name: inlist_project

# --- Analysis and Plotting Options ---
# Set these to True ONLY for the specific tasks you want to perform.

# This is CRITICAL. The blue loop BC plots rely on the detailed
# blue loop analysis data, which is generated when this is True.
# Keep this as True to ensure the necessary data is processed.
analyze_blue_loop: False

# Set to False to ensure no heatmaps are generated.
generate_heatmaps: False

# This explicitly tells the program NOT to generate general HRD plots.
# This should prevent the "összes HRD-t kirajzolja" issue.
generate_plots: False

# This is what you want! Set to True to generate the blue loop specific
# HRD/CMD/logg-L plots with bolometric corrections.
generate_blue_loop_plots_with_bc: True

# --- Other Settings ---
# If you've run a full analysis before and the 'detail_z*.csv' files exist,
# you can set 'force_reanalysis' to False to speed things up.
# If you want to re-run the blue loop analysis from scratch, set it to True.
force_reanalysis: False

# Defines the columns saved in the detailed blue loop CSV files.
# 'all' saves all columns from the blue loop phase.
# 'summary' saves only key columns (e.g., star_age, log_Teff, log_L).
blue_loop_output_type: summary

# --- Blue Loop Plotting Specifics (Optional, add as needed) ---
# It's good practice to add any parameters specific to generate_blue_loop_plots_with_bc
# directly under plot_settings if your CLI handles it this way.
# Example:
# plot_settings:
#   mass_filter: 1.5 # Specific mass to plot blue loops for
#   plots_output_subdir: "blue_loop_bc_plots" # Subdirectory within output_dir for these plots